# These are supported funding model platforms

github: Mahmoudgalalz
open_collective: # Replace with a single Open Collective username
ko_fi: Mahmoudgalal
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
