name: Crawler runner

on:
  workflow_dispatch:
      
jobs:
  build_crawler:
    name: Running the Crawler
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen
        

  Backend:
    name: Looking for a Backend EntryLevel
    needs: build_crawler
    runs-on: ubuntu-latest
    env:
      MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
      LIMIT: ${{ secrets.LIMIT }}
      TITLES: 'Backend'
      LOCATIONS: 'Egypt'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen

      - name: Run the Backend Scrapping
        run: npm run start entry


  Frontend:
    name: Looking for a Frontend EntryLevel
    needs: build_crawler
    runs-on: ubuntu-latest
    env:
      MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
      LIMIT: ${{ secrets.LIMIT }}
      TITLES: 'Frontend'
      LOCATIONS: 'Egypt'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen

      - name: Run the Frontend Scrapping
        run: npm run start entry
  SW:
    name: Looking for a Software Engineer EntryLevel
    needs: build_crawler
    runs-on: ubuntu-latest
    env:
      MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
      LIMIT: ${{ secrets.LIMIT }}
      TITLES: 'Software Engineer'
      LOCATIONS: 'Egypt'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen

      - name: Run the Software Engineer Scrapping
        run: npm run start entry
  InternBack:
    name: Looking for a Backend Internship
    needs: build_crawler
    runs-on: ubuntu-latest
    env:
      MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
      LIMIT: ${{ secrets.LIMIT }}
      TITLES: 'Backend'
      LOCATIONS: 'Egypt'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen

      - name: Run the Backend Intern Scrapping
        run: npm run start intern
  InternFront:
    name: Looking for a Frontend intern
    needs: build_crawler
    runs-on: ubuntu-latest
    env:
      MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
      LIMIT: ${{ secrets.LIMIT }}
      TITLES: 'Backend'
      LOCATIONS: 'Egypt'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen

      - name: Run the Backend Scrapping
        run: npm run start intern
  InternSW:
    name: Looking for a Software Engineer intern
    needs: build_crawler
    runs-on: ubuntu-latest
    env:
      MAIN_DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
      LIMIT: ${{ secrets.LIMIT }}
      TITLES: 'Software Engineer'
      LOCATIONS: 'Egypt'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      
      - name: generate types of prisma
        run: npm run gen

      - name: Run the Software Engineer Scrapping
        run: npm run start intern